version: "3"

services:    
    database:
      image: mongo
      restart: always
      volumes:
        - ~\Natan\Documents\mongo\data:/data/db
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: inn