version: "3"

services:    
    database:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: inn
    messageQ:
      image : rabbitmq:3-management
      container_name: rabbitmqManager
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - 15672:15672
        - 5672:5672
      restart: always
      